from loguru import logger as _logger
from tqdm import tqdm as _tqdm

_logger.remove()


def _tqdm_sink(message):
    record = message.record
    if record['level'].no >= 30 or record['extra'].get('force'):
        _tqdm.write(str(message), end='')


_logger.add(_tqdm_sink, format='{time:HH:mm:ss} | {level: <8} | {message}')

from .audio import Audio, AudioChapter, AudioVolume
from .auth import Auth
from .base import Container, Item, Section
from .comic import Comic, ComicChapter
from .config import (
    API_BOOK,
    API_COMIC_PICS,
    API_COMIC_VIP,
    API_HTML5,
    API_LOLOBUN,
    API_LOLOBUN_COMIC,
    API_VIP_IMAGE,
    AUDIOBOOKS_JSON,
    COMIC_BASE,
    COMIC_READER_BASE,
    COOKIE_PATH,
    DEFAULT_DELAY,
    MAX_RETRIES,
    MOBILE_BASE,
    OCR_BRIGHTNESS_THRESHOLD,
    OCR_STRIP_HEIGHT,
    OCR_WORKERS,
    PASSPORT_BASE,
    PC_BASE,
    SELECTORS_PATH,
    TIMEOUT,
    URL_AUDIO,
    URL_COMIC_INDEX,
    URL_NOVEL_INDEX,
    URL_REVIEW_DETAIL,
    URL_REVIEW_LIST,
    VIP_IMAGE_WIDTH,
    WORKERS_AUDIO_CHAPTER,
    WORKERS_AUDIO_VOLUME,
    WORKERS_CHAPTER,
    WORKERS_EPUB_IMG,
    WORKERS_IMAGE,
    Settings,
    VipMode,
    settings,
)
from .fetcher import Fetcher
from .lolobun_comic import LoLoBunComic, LoLoBunComicChapter
from .lolobun_novel import LoLoBunNovel, LoLoBunNovelChapter
from .models import (
    AudioCatalog,
    AudioCatalogItem,
    AudioCatalogSection,
    Catalog,
    CatalogItem,
    CatalogSection,
    ComicCatalog,
    ComicCatalogSection,
    LoLoBunComicCatalog,
    LoLoBunComicCatalogSection,
    LoLoBunNovelCatalog,
    LoLoBunNovelCatalogItem,
    LoLoBunNovelCatalogSection,
    NovelCatalog,
    NovelCatalogItem,
    NovelCatalogSection,
    ReviewCatalog,
    ReviewCatalogSection,
    SearchItem,
)
from .novel import Novel, NovelChapter, Review
from .ocr import (
    ChatBot,
    interactive_chat,
    merge_wrapped_lines,
    ocr_bytes,
    ocr_gif,
    ocr_image,
    remove_pinyin,
    remove_pinyin_gif,
    remove_pinyin_to_bytes,
)
from .search import (
    NovelItem,
    get_author_works,
    get_related,
    predictive_comic,
    predictive_novel,
    search,
    search_comic,
    search_comic_api,
    search_lolobun,
    search_lolobun_comic,
    search_lolobun_novel,
    search_novel,
    search_novel_api,
)
from .selectors import SelectorError, Selectors
from .utils import mobile_url, parse_volume_ul, run_tasks, sanitize_filename, validate_gif
from .utils.epub import convert_html_to_epub, convert_md_to_epub, download_epub

__all__ = [
    'API_BOOK',
    'Audio',
    'AudioCatalog',
    'AudioCatalogItem',
    'AudioCatalogSection',
    'AudioChapter',
    'AudioVolume',
    'Auth',
    'Catalog',
    'CatalogItem',
    'CatalogSection',
    'ChatBot',
    'Comic',
    'ComicCatalog',
    'ComicCatalogSection',
    'ComicChapter',
    'Container',
    'Fetcher',
    'Item',
    'LoLoBunComic',
    'LoLoBunComicCatalog',
    'LoLoBunComicCatalogSection',
    'LoLoBunComicChapter',
    'LoLoBunNovel',
    'LoLoBunNovelCatalog',
    'LoLoBunNovelCatalogItem',
    'LoLoBunNovelCatalogSection',
    'LoLoBunNovelChapter',
    'Novel',
    'NovelCatalog',
    'NovelCatalogItem',
    'NovelCatalogSection',
    'NovelChapter',
    'NovelItem',
    'OCR_BRIGHTNESS_THRESHOLD',
    'OCR_STRIP_HEIGHT',
    'OCR_WORKERS',
    'ReviewCatalog',
    'ReviewCatalogSection',
    'SearchItem',
    'Section',
    'SelectorError',
    'Selectors',
    'Settings',
    'VIP_IMAGE_WIDTH',
    'VipMode',
    'convert_html_to_epub',
    'convert_md_to_epub',
    'download_epub',
    'get_author_works',
    'get_related',
    'interactive_chat',
    'merge_wrapped_lines',
    'mobile_url',
    'ocr_bytes',
    'ocr_gif',
    'ocr_image',
    'parse_volume_ul',
    'predictive_comic',
    'predictive_novel',
    'remove_pinyin',
    'remove_pinyin_gif',
    'remove_pinyin_to_bytes',
    'run_tasks',
    'sanitize_filename',
    'search',
    'search_comic',
    'search_comic_api',
    'search_lolobun',
    'search_lolobun_comic',
    'search_lolobun_novel',
    'search_novel',
    'search_novel_api',
    'settings',
    'validate_gif',
]
